# Generated by Django 5.0 on 2024-01-11 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetasBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recetas_ingresadas',
            name='ingredientes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recetas_ingresadas',
            name='cantidad_de_comensales',
            field=models.CharField(max_length=10),
        ),
    ]
