# Generated by Django 5.0 on 2024-01-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetasBlog', '0004_ingreso_al_blog_alter_usuario_ingresado_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='info_de_contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre_Completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('consulta', models.CharField(max_length=6000)),
            ],
        ),
    ]
