# Generated by Django 5.0 on 2024-01-29 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetasBlog', '0005_info_de_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='editar_receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=20)),
                ('ingrediente_principal', models.CharField(max_length=100)),
                ('ingredientes', models.TextField()),
                ('procedimiento', models.CharField(max_length=2000)),
                ('cantidad_de_comensales', models.CharField(max_length=10)),
            ],
        ),
    ]
