# Generated by Django 5.0 on 2024-01-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetasBlog', '0006_editar_receta'),
    ]

    operations = [
        migrations.DeleteModel(
            name='editar_receta',
        ),
        migrations.AddField(
            model_name='recetas_ingresadas',
            name='id_receta',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='recetas_ingresadas',
            name='cantidad_de_comensales',
            field=models.IntegerField(max_length=10),
        ),
    ]
