# Generated by Django 5.0 on 2024-02-01 12:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetasBlog', '0007_delete_editar_receta_recetas_ingresadas_id_receta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetas_ingresadas',
            name='id_receta',
        ),
        migrations.AddField(
            model_name='ingreso_al_blog',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='recetas_ingresadas',
            name='procedimiento',
            field=models.TextField(),
        ),
    ]
