# Generated by Django 5.0 on 2024-01-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recetas_ingresadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=20)),
                ('ingrediente_principal', models.CharField(max_length=100)),
                ('procedimiento', models.CharField(max_length=2000)),
                ('cantidad_de_comensales', models.DateField(max_length=10)),
            ],
        ),
    ]
