# Generated by Django 5.0 on 2024-01-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppRecetasBlog', '0003_usuario_ingresado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ingreso_al_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('tema', models.CharField(max_length=1000)),
                ('historia', models.CharField(max_length=6000)),
            ],
        ),
        migrations.AlterField(
            model_name='usuario_ingresado',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
